# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23954ba1fbf00ce82547d87c68855094099ef2b0d74bcbd4203b70f044a882bc5ed6a82aca6145c150428bc92eac934cc09eb0a586aa26dccaf2ed5b0a44c749

test:
  secret_key_base: 700de7ee4b36b1ca2b8692aac15c8f61ef875692ebb8482195f6c056693dfda08f3810f6802b7779734cb3ed9d1306b1e8270809e4e4ca68417bf44eff592147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
